"""
Interface to hold contents of api responses when they do not confirm
to the OpenAI style response.
"""

from collections.abc import AsyncGenerator
from dataclasses import dataclass, field
from typing import Any, Literal, Union

from pydantic import BaseModel


class Function(BaseModel):
    """Represents a function call."""

    arguments: str
    name: str


class ChatCompletionMessageToolCall(BaseModel):
    """Represents a tool call in a chat completion message."""

    id: str
    function: Function
    type: Literal["function"]


class Message(BaseModel):
    """Represents a message in a chat completion."""

    content: str | None = None
    reasoning_content: str | None = None
    tool_calls: list[ChatCompletionMessageToolCall] | None = None
    role: Literal["user", "assistant", "system", "tool"] | None = None
    refusal: str | None = None


class CompletionTokensDetails(BaseModel):
    """Details about the tokens used in a completion."""

    accepted_prediction_tokens: int | None = None
    """
    When using Predicted Outputs, the number of tokens in the prediction that
    appeared in the completion.
    """

    audio_tokens: int | None = None
    """Audio input tokens generated by the model."""

    reasoning_tokens: int | None = None
    """Tokens generated by the model for reasoning."""

    rejected_prediction_tokens: int | None = None
    """
    When using Predicted Outputs, the number of tokens in the prediction that did
    not appear in the completion. However, like reasoning tokens, these tokens are
    still counted in the total completion tokens for purposes of billing, output,
    and context window limits.
    """


class PromptTokensDetails(BaseModel):
    """Details about the tokens used in a prompt."""

    text_tokens: int | None = None
    """Tokens generated by the model for text."""

    audio_tokens: int | None = None
    """Audio input tokens present in the prompt."""

    cached_tokens: int | None = None
    """Cached tokens present in the prompt."""


class CompletionUsage(BaseModel):
    """Represents the token usage for a completion."""

    completion_tokens: int | None = None
    """Number of tokens in the generated completion."""

    prompt_tokens: int | None = None
    """Number of tokens in the prompt."""

    total_tokens: int | None = None
    """Total number of tokens used in the request (prompt + completion)."""

    completion_tokens_details: CompletionTokensDetails | None = None
    """Breakdown of tokens used in a completion."""

    prompt_tokens_details: PromptTokensDetails | None = None
    """Breakdown of tokens used in the prompt."""


class Word(BaseModel):
    """Represents a single word with timing information."""

    word: str
    start: float
    end: float
    confidence: float | None = None  # Common across Deepgram, Azure, AWS
    speaker: int | None = None  # Speaker diarization (Deepgram, Azure, AWS)
    speaker_confidence: float | None = None  # Speaker identification confidence
    punctuated_word: str | None = None  # Word with punctuation (some providers)


class Segment(BaseModel):
    """Represents a segment of transcribed text with detailed information."""

    id: int
    seek: int
    start: float
    end: float
    text: str
    # OpenAI Whisper specific fields
    tokens: list[int] | None = None
    temperature: float | None = None
    avg_logprob: float | None = None
    compression_ratio: float | None = None
    no_speech_prob: float | None = None
    # Common ASR provider fields
    confidence: float | None = None  # Segment-level confidence
    speaker: int | None = None  # Primary speaker for this segment
    speaker_confidence: float | None = None  # Speaker identification confidence
    words: list[Word] | None = None  # Words within this segment


class Alternative(BaseModel):
    """Represents an alternative transcription hypothesis (common in many ASR APIs)."""

    transcript: str
    confidence: float | None = None
    words: list[Word] | None = None


class Channel(BaseModel):
    """Represents a single audio channel (for multi-channel audio)."""

    alternatives: list[Alternative]
    search: list[dict] | None = None  # Search results if keyword search enabled


class TranscriptionResult(BaseModel):
    """
    Unified transcription result format supporting multiple ASR providers.
    Based on OpenAI Whisper API but extended for common ASR features.
    """

    # Core fields (supported by most providers)
    text: str
    language: str | None = None
    confidence: float | None = None  # Overall transcription confidence

    # OpenAI Whisper specific fields
    task: str | None = None  # "transcribe" or "translate"
    duration: float | None = None
    segments: list[Segment] | None = None
    words: list[Word] | None = None

    # Multi-channel and alternatives support (Deepgram, Azure, etc.)
    channels: list[Channel] | None = None
    alternatives: list[Alternative] | None = None

    # Advanced features (various providers)
    utterances: list[dict] | None = None  # Speaker utterances
    paragraphs: list[dict] | None = None  # Paragraph detection
    topics: list[dict] | None = None  # Topic detection
    intents: list[dict] | None = None  # Intent recognition
    sentiment: dict | None = None  # Sentiment analysis
    summary: dict | None = None  # Auto-summarization

    # Metadata
    metadata: dict | None = None  # Provider-specific metadata
    model_info: dict | None = None  # Model information


class StreamingTranscriptionChunk(BaseModel):
    """Represents a single chunk of streaming transcription data."""

    text: str
    is_final: bool
    confidence: float | None = None
    start_time: float | None = None
    end_time: float | None = None
    speaker_id: int | None = None
    speaker_confidence: float | None = None
    words: list[Word] | None = None
    sequence_number: int | None = None
    channel: int | None = None
    provider_data: dict | None = None


# Type alias for streaming transcription responses
StreamingTranscriptionResponse = AsyncGenerator[StreamingTranscriptionChunk, None]

# Union type for both batch and streaming responses
TranscriptionResponse = Union[TranscriptionResult, StreamingTranscriptionResponse]


@dataclass
class TranscriptionOptions:
    """Unified transcription options for ASR providers."""

    # Core parameters
    language: str | None = None

    # Audio format parameters
    audio_format: str | None = None
    sample_rate: int | None = None
    channels: int | None = None
    encoding: str | None = None  # Audio encoding type

    # Output format
    response_format: str | None = None
    include_word_timestamps: bool | None = None
    include_segment_timestamps: bool | None = None
    timestamp_granularities: list[str] | None = None  # OpenAI: ["word", "segment"]

    # Context and guidance
    prompt: str | None = None
    context_phrases: list[str] | None = None
    boost_phrases: list[str] | None = None

    # Speaker features
    enable_speaker_diarization: bool | None = None
    max_speakers: int | None = None
    min_speakers: int | None = None

    # Text processing
    enable_automatic_punctuation: bool | None = None
    enable_profanity_filter: bool | None = None
    enable_smart_formatting: bool | None = None
    enable_word_confidence: bool | None = None
    enable_spoken_punctuation: bool | None = None
    enable_spoken_emojis: bool | None = None

    # Advanced features
    enable_sentiment_analysis: bool | None = None
    enable_topic_detection: bool | None = None
    enable_intent_recognition: bool | None = None
    enable_summarization: bool | None = None
    enable_translation: bool | None = None
    translation_target_language: str | None = None

    # Confidence and alternatives
    include_confidence_scores: bool | None = None
    max_alternatives: int | None = None

    # Processing options
    temperature: float | None = None
    interim_results: bool | None = None
    vad_sensitivity: float | None = None
    stream: bool | None = None  # Enable streaming output

    # Custom parameters
    custom_parameters: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Validate parameters and constraints."""
        # Validate constraints
        if self.temperature is not None and not (0.0 <= self.temperature <= 1.0):
            raise ValueError("temperature must be between 0.0 and 1.0")

        if self.max_speakers is not None and self.max_speakers < 1:
            raise ValueError("max_speakers must be at least 1")

        if self.min_speakers is not None and self.min_speakers < 1:
            raise ValueError("min_speakers must be at least 1")

        if (
            self.max_speakers is not None
            and self.min_speakers is not None
            and self.min_speakers > self.max_speakers
        ):
            raise ValueError("min_speakers cannot be greater than max_speakers")

        if self.vad_sensitivity is not None and not (
            0.0 <= self.vad_sensitivity <= 1.0
        ):
            raise ValueError("vad_sensitivity must be between 0.0 and 1.0")

    def has_any_parameters(self) -> bool:
        """Check if any parameters are set."""
        for field_name, field_value in self.__dict__.items():
            if field_name == "custom_parameters":
                if field_value:
                    return True
            elif field_value is not None:
                return True
        return False

    def get_set_parameters(self) -> dict[str, Any]:
        """Get only the parameters that are set."""
        set_params = {}
        for field_name, field_value in self.__dict__.items():
            if field_name == "custom_parameters":
                if field_value:
                    set_params[field_name] = field_value
            elif field_value is not None:
                set_params[field_name] = field_value
        return set_params
